config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :posts
  resources :users
  
  root 'home#top'
  get 'user/new'
  get 'users/:id' => 'users#show'
  get "users/:id/edit" => "users#edit"
  post 'users/create' => 'users#create'
  get 'top' => "home#top"
  post "about" => "home#about"
  get 'signup'  => 'users#new'
  post 'signup'  => 'users#new'
  delete 'logout' => "users#destroy"
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # emailを小文字に変換して保存
  before_save { self.email = email.downcase }
  
  # バリデーションチェック
  validates :name, 
            presence: true, 
            length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, 
            presence: true, 
            length: { maximum: 255 }, 
            format: { with: VALID_EMAIL_REGEX }, 
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  protect_from_forgery with: :exception

  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # def initialize
  # end

  def index
    # @posts = Post.all.order(created_at: 'desc')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in user
      redirect_to user
    else
      # エラーメッセージを作成する
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "ユーザーを追加しました。"
      redirect_to("/users/#{@user.id}")
    else
      # flash.now[:danger] = "ユーザー登録をお願いします。"
      render 'new'
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
  end

  def destroy
  end

  def user_params
   params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :twitter, :linkedin, :line)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 現在ログインしているユーザーを返す (ユーザーがログイン中の場合のみ)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/home/about.html.erb
<html>
<body>
  <p>職務経歴は<a href="https://www.resume.id/shinya_ishizaki">こちら</a></p>
</body>
</html>

app/views/home/enter.html.erb
<form accept-charset="UTF-8" action="/login" method="post">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input name="authenticity_token" type="hidden"
         value="NNb6+J/j46LcrgYUC60wQ2titMuJQ5lLqyAbnbAUkdo=" />
  <label for="session_email">Email</label>
  <input class="form-control" id="session_email"
         name="session[email]" type="text" />
  <label for="session_password">Password</label>
  <input id="session_password" name="session[password]"
         type="password" />
  <input class="btn btn-primary" name="commit" type="submit"
       value="Log in" />
</form>

app/views/home/top.html.erb
<html>
  <head>
  <link rel="stylesheet" href="../../../aseets/fontawesome/css/all.css">
  </head>
  <body>
    <div class="main top-main">
      <div class="top-message">
        <h2>Shinya Ishizaki&#39;s Portfolio</h2>
      </div>
      <div>
        <p>しんや（石崎慎弥）</p>
        <p>フリーランスエンジニア</p>
      </div>
      <div>
        <h3>キャリア略歴</h3>
        <p>損害保険会社、生命保険会社、銀行向け営業店・代理店システム保守開発に4年携わる。<br>
        他業種他職種を経て独立。<br>
        Web系エンジニアとして活動するとともに、プログラミング初心者のメンターとしてエンジニアの育成にも力を入れる。</p>
      </div>
      <div>
        <h3>SNSはこちら</h3>
        <div class="sns-parent">
          <div class="sns-child">
            <p><a href="https://twitter.com/Shinyaaah0311" target="_blank"><i class="fa fa-twitter aria-hidden="true""></i></a></p>
          </div>
          <div class="sns-child">
            <p><a href="https://www.linkedin.com/in/shinyaishizaki0311/" target="_blank"><i class="fa fa-linkedin aria-hidden="true""></i></a></p>
          </div>
          <div class="sns-child">
            <a href="https://lin.ee/hscs5VS"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"" class="fa-brands fa-line"></a>
          </div>
        </div>
      </div>
      <div>
        <h3>プログラミング学習のメンター依頼は<a href="https://menta.work/user/39158" target="_blank">こちら</a></h3>
      </div>
    </div>
    <button type="button" onclick="location.href='login'">会員様はこちらからご入室ください</button>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>My Portfolio | <%= yield(:title) %></title>
<%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>

app/views/posts/index.html.erb
<h2>My Posts</h2>
<ul>
# <% @posts.each do |post| %>
# <li><%= post.title %></li>
# <% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>My Portfolio</h1>
<p>
  This is the home page for Shinya Ishizaki&39; Portfolio
</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>